introspection: http://localhost:4000/graphql
servers:
  - url: https://try-api.wunder-insurance.com
    description: Wunder Insurance Try-API Gateway (after registration)

info:
  title: Wunder Insurance API - Commercial Motor Insurance
  description: |
    This is an excerpt from the ActiveInsurance API documentation. 

    You can use the Wunder Insurance Try-API Gateway to get quotes for this insurance product. 
    ActiveInsurance is a GraphQL API but can also be accessed via REST. 

    Feel free to contact us at info@wunder-insurance.com

  version: 1.0.0
  termsOfService: 'https://wunder-insurance.com/terms'
  contact:
    email: info@wunder-insurance.com
  license:
    name: Commercial
    url: 'https://wunder-insurance.com/terms'
domains:
  - name: Commercial Motor Product
    description: Insurance for fleet vehicles
    usecases:
    - name: Create Quote      
      query: mutation.CommercialMotorQuote
    - name: Create Policy
      query: mutation.CommercialMotorPolicy
    - name: Get Quote
      query: query.commercialMotorQuoteQuery
    - name: Get Policy
      query: query.commercialMotorPolicyQuery
  - name: Identities
    description: You can define custom entities for your business domain. These are some example entities used in this product
    usecases:
      - name: Address
        description: Returns list of addresses. Address is an entity according to your business domain
        query: query.addresses
      - name: Truck
        description: Returns list of trucks. Truck is an entity according to your business domain
        query: query.trucks
      - name: Person
        description: Returns list of persons. Person is an entity according to your business domain
        query: query.people

